[workspace]

members = [
    "async-closures",
    "bridging-async-and-sync",
    "combinator",
    "composite-pattern",
    "generator",
    "iterator",
    "lifetime",
    "newtype",
    "self-ref",
]
